import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Header from './components/Navbar';
import { VStack, Box } from '@chakra-ui/react';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Nunito({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={inter.className}>
      <VStack spacing={0} align="stretch">
        <Header />
        <Box mt={20} px={6}>
          {children}
        </Box>
      </VStack>
    </main>
  );
}
